#项目设置
rest:
  swagger-open: true               #是否开启swagger (true/false)
  sign-open: false                  #是否开启数据签名验证
  auth-open: true                  #是否开启jwt
  send-limit: 10                   #每日发送短信数量
  project-url: http://58.56.184.202:60000/asmall-rest             #项目回调地址
  we-chat-public-address-app-id: wxdead3a2b6d67c0e7          #微信公众号appId
  we-chat-public-address-app-secret: eebf807092dedd891561bd774d3fbe65          #微信公众号appSecret
  we-chat-front-callback-url: http://www.iseemall.com.cn/pages/set/wxblock/wxblock              #获取openid生成token后回调此地址

#阿里云设置
aliyun:
  oss: #OSS配置
    endpoint: oss-cn-zhangjiakou.aliyuncs.com           #访问域名
    accessKeyId: LTAI4FfygTTGWS5JVFVG1Z5V               #访问ID
    accessKeySecret: DgUCyeQuY0cJIEkSsPFMnZVGbJY7xN     #访问密钥
    bucketName: asmall-test                             #存储空间
    dir: test/                                          #存储目录
  sms: #短信配置
    region-id: cn-hangzhou                                  #地区id
    access-key-id: LTAI4FfygTTGWS5JVFVG1Z5V                     #访问id
    access-key-secret: DgUCyeQuY0cJIEkSsPFMnZVGbJY7xN   #访问秘钥
    domain: dysmsapi.aliyuncs.com                       #域名
    template-code: SMS_176555254                        #模板名称
    day-limit: 10                                       #每日短信发送限制
spring:
  datasource:
    url: jdbc:mysql://192.168.1.254:3306/asmall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: SL_docker@mysql2802
    db-name: asmall #用来搜集数据库的所有表
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  output:
    ansi:
      enabled: always
  #spring-redis设置
  redis:
    #数据库索引
    database: 0
    host: 192.168.1.254
    port: 6379
    password:
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间(毫秒)
    timeout: 3600
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.1.254:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 20
    packages:
      trust-all: true   #是否信任所有包，信任后所有包内的对象均可序列化传输
    queue-name: asmall.test.message.queue   #默认队列名称
#通联支付配置
allinpay:
  server-url: https://fintech.allinpay.com/service/soa    #接口地址
  version: 2.0                                         #接口版本
  sys-id: 1912131617401390151                          #应用系统编号
  path: ${user.home}/1912131617401390151.pfx  #私钥证书路径
  pwd: 9789395384                                      #证书密码
  alias: 1912131617401390151                           #别名
  account-set-no: 400295                               #托管账户集编号
  sub-app-id: wxdead3a2b6d67c0e7                       #微信端应用id
  tl-cert-path: ${user.home}/TLCert-prod.cer  #生产环境请使用生产证书
  sign-contract-url: https://fintech.allinpay.com/yungateway/member/signContract.html #电子协议签约地址
  set-pay-pwd-url: https://fintech.allinpay.com/yungateway/pwd/setPayPwd.html #设置支付密码地址
  update-pay-pwd-url: https://fintech.allinpay.com/yungateway/pwd/updatePayPwd.html #修改支付密码地址
  reset-pay-pwd-url: https://fintech.allinpay.com/yungateway/pwd/resetPayPwd.html #重置支付密码地址
  pay-order-url: https://fintech.allinpay.com/yungateway/frontTrans.do      #确认支付（前台+短信验证验证版）
  pay-confirm-password-url: https://fintech.allinpay.com/yungateway/pwd/payOrder.html #密码验证确认支付
  biz-user-id: STz5z7z5910184011                     #分账人
  ###################################################快捷签#################################################
  #存证FTL/Html/PDF存放路径
  ##项目ID(公共应用ID)-模拟环境,正式环境下贵司将拥有独立的应用ID
eqb:

  #公司印章
  aisai-seal: /usr/local/template/contract/protocol/aisai.png

  #法人印章
  legal-seal: /usr/local/template/contract/protocol/fr.png

  #合同模板服务器路径
  template-path: /usr/local/template/contract/

  #字体路径
  font-path: /usr/local/template/contract/font/SIMSUN.TTC

  project-id: 4438791399

  ## 项目Secret(公共应用Secret)-模拟环境,正式环境下贵司将拥有独立的应用Secret
  project-secret: 7fa4ffc1bb49960ff624553c39167436

  ##测试环境地址
  api-host: https://smlopenapi.esign.cn

  #异步通知地址
  notice-developer-url: http://58.56.184.202:60000/asmall-rest/eqbContract/contractCallBack
